<?php

namespace App\Services\Reports\Exports;

use PhpOffice\PhpSpreadsheet\Cell\DataType;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

final class ReportExcelExporter
{
    public function download(array $report, string $filename)
    {
        return response()->streamDownload(function () use ($report): void {
            $spreadsheet = new Spreadsheet;
            $sheet = $spreadsheet->getActiveSheet();
            $sheet->setTitle('Report');

            if (! empty($report['sections'])) {
                $this->writeDynamicWorkbook($spreadsheet, $report);
            } else {

            $columnCount = max(count($report['columns']), 1);
            $lastColumn = $this->columnName($columnCount);

            $sheet->mergeCells("A1:{$lastColumn}1");
            $sheet->setCellValue('A1', $report['title']);
            $sheet->getStyle("A1:{$lastColumn}1")->applyFromArray([
                'font' => ['bold' => true, 'size' => 16, 'color' => ['rgb' => '1E3A8A']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
            ]);

            $sheet->mergeCells("A2:{$lastColumn}2");
            $sheet->setCellValue('A2', 'Reporting period: '.$report['period']);
            $sheet->mergeCells("A3:{$lastColumn}3");
            $sheet->setCellValue('A3', 'Generated on: '.($report['generated_at_label'] ?? $report['generated_at']).' | Generated by: '.$report['generated_by']);

            $rowNumber = 5;
            $sheet->setCellValue("A{$rowNumber}", 'Applied filters');
            $sheet->getStyle("A{$rowNumber}:B{$rowNumber}")->getFont()->setBold(true);
            $rowNumber++;
            foreach ($report['filters'] as $label => $value) {
                $sheet->setCellValue("A{$rowNumber}", $label);
                $this->setTypedCell($sheet, "B{$rowNumber}", $value, 'text');
                $rowNumber++;
            }

            if (! empty($report['summary'])) {
                $rowNumber++;
                $sheet->setCellValue("A{$rowNumber}", 'Summary');
                $sheet->getStyle("A{$rowNumber}:B{$rowNumber}")->getFont()->setBold(true);
                $rowNumber++;
                foreach ($report['summary'] as $label => $value) {
                    $sheet->setCellValue("A{$rowNumber}", str_replace('_', ' ', $label));
                    $sheet->setCellValue("B{$rowNumber}", is_numeric($value) ? (float) $value : (string) $value);
                    $rowNumber++;
                }
            }

            $rowNumber += 1;
            $headerRow = $rowNumber;
            foreach ($report['columns'] as $index => $column) {
                $sheet->setCellValue($this->columnName($index + 1).$headerRow, $column['label']);
            }

            $sheet->getStyle("A{$headerRow}:{$lastColumn}{$headerRow}")->applyFromArray([
                'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
                'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1D4ED8']],
                'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
                'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'CBD5E1']]],
            ]);

            $writtenRows = 0;
            foreach ($report['rows'] as $row) {
                $writtenRows++;
                $excelRow = $headerRow + $writtenRows;
                foreach ($report['columns'] as $columnIndex => $column) {
                    $cell = $this->columnName($columnIndex + 1).$excelRow;
                    $value = $row[$column['key']] ?? '';
                    $type = $column['type'] ?? 'text';

                    if (in_array($type, ['integer', 'number', 'percentage'], true) && is_numeric($value)) {
                        $numericValue = $type === 'percentage'
                            ? (float) $value / 100
                            : (float) $value;
                        $sheet->setCellValue($cell, $numericValue);
                        if ($type === 'percentage') {
                            $sheet->getStyle($cell)->getNumberFormat()->setFormatCode('0.00%');
                        }
                    } else {
                        $sheet->setCellValueExplicit($cell, $this->safeText($value), DataType::TYPE_STRING);
                    }
                }
            }

            $lastDataRow = $headerRow + max($writtenRows, 1);
            $sheet->freezePane("A".($headerRow + 1));
            $sheet->setAutoFilter("A{$headerRow}:{$lastColumn}{$lastDataRow}");
            $sheet->getStyle("A{$headerRow}:{$lastColumn}{$lastDataRow}")->getAlignment()->setVertical(Alignment::VERTICAL_TOP);
            $sheet->getStyle("A{$headerRow}:{$lastColumn}{$lastDataRow}")->getAlignment()->setWrapText(true);

            foreach ($report['columns'] as $index => $column) {
                $letter = $this->columnName($index + 1);
                $sheet->getColumnDimension($letter)->setWidth($column['key'] === 'diagnosis' || $column['key'] === 'diagnoses' ? 36 : 18);
            }
            }

            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
            $spreadsheet->disconnectWorksheets();
        }, $filename, [
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        ]);
    }

    private function writeDynamicWorkbook(Spreadsheet $spreadsheet, array $report): void
    {
        $summary = $spreadsheet->getActiveSheet();
        $summary->setTitle('Summary');
        $summary->mergeCells('A1:D1');
        $summary->setCellValue('A1', $report['title']);
        $summary->getStyle('A1:D1')->applyFromArray([
            'font' => ['bold' => true, 'size' => 16, 'color' => ['rgb' => '1E3A8A']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);
        $summary->mergeCells('A2:D2');
        $summary->setCellValue('A2', 'Reporting period: '.$report['period']);
        $summary->mergeCells('A3:D3');
        $summary->setCellValue('A3', 'Generated on: '.($report['generated_at_label'] ?? $report['generated_at']).' | Generated by: '.$report['generated_by']);

        $rowNumber = 5;
        $summary->setCellValue("A{$rowNumber}", 'Applied filters');
        $summary->getStyle("A{$rowNumber}")->getFont()->setBold(true);
        $rowNumber++;
        foreach ($report['filters'] as $label => $value) {
            $summary->setCellValue("A{$rowNumber}", $label);
            $this->setTypedCell($summary, "B{$rowNumber}", $value, 'text');
            $rowNumber++;
        }

        foreach ($report['sections'] as $section) {
            if (($section['kind'] ?? '') === 'table') {
                $this->writeDynamicTableSheet($spreadsheet, $section);
                continue;
            }

            $rowNumber++;
            $summary->setCellValue("A{$rowNumber}", $section['title']);
            $summary->getStyle("A{$rowNumber}")->getFont()->setBold(true);
            $rowNumber++;

            if (($section['kind'] ?? '') === 'text') {
                $summary->mergeCells("A{$rowNumber}:D{$rowNumber}");
                $summary->setCellValue("A{$rowNumber}", $section['text'] ?? '');
                $rowNumber++;
            } elseif (($section['kind'] ?? '') === 'metrics') {
                foreach ($section['metrics'] ?? [] as $metric) {
                    $summary->setCellValue("A{$rowNumber}", $metric['label']);
                    $this->setTypedCell($summary, "B{$rowNumber}", $metric['value'] ?? '', $metric['type'] ?? 'text');
                    $rowNumber++;
                }
            } elseif (($section['kind'] ?? '') === 'list') {
                foreach ($section['items'] ?? [] as $item) {
                    $summary->mergeCells("A{$rowNumber}:D{$rowNumber}");
                    $summary->setCellValue("A{$rowNumber}", '• '.$item);
                    $rowNumber++;
                }
            }
        }

        $summary->getColumnDimension('A')->setWidth(30);
        $summary->getColumnDimension('B')->setWidth(48);
        $summary->getColumnDimension('C')->setWidth(18);
        $summary->getColumnDimension('D')->setWidth(18);
        $summary->getStyle('A1:D'.$rowNumber)->getAlignment()->setWrapText(true);
    }

    private function writeDynamicTableSheet(Spreadsheet $spreadsheet, array $section): void
    {
        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle($this->safeSheetTitle($section['title'], $spreadsheet));
        $columns = $section['columns'] ?? [];
        $lastColumn = $this->columnName(max(count($columns), 1));
        $headerRow = 1;

        foreach ($columns as $index => $column) {
            $sheet->setCellValue($this->columnName($index + 1).$headerRow, $column['label']);
        }

        $sheet->getStyle("A{$headerRow}:{$lastColumn}{$headerRow}")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1D4ED8']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders' => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['rgb' => 'CBD5E1']]],
        ]);

        $rowNumber = 2;
        foreach ($section['rows'] ?? [] as $row) {
            foreach ($columns as $index => $column) {
                $this->setTypedCell($sheet, $this->columnName($index + 1).$rowNumber, $row[$column['key']] ?? '', $column['type'] ?? 'text');
            }
            $rowNumber++;
        }

        $lastDataRow = max($rowNumber - 1, $headerRow);
        $sheet->freezePane('A2');
        $sheet->setAutoFilter("A{$headerRow}:{$lastColumn}{$lastDataRow}");
        $sheet->getStyle("A{$headerRow}:{$lastColumn}{$lastDataRow}")->getAlignment()->setWrapText(true);
        foreach ($columns as $index => $column) {
            $sheet->getColumnDimension($this->columnName($index + 1))->setWidth(
                in_array($column['key'], ['diagnosis', 'diagnoses', 'patient_name', 'destination_hospital'], true) ? 36 : 18,
            );
        }
    }

    private function setTypedCell($sheet, string $cell, mixed $value, string $type): void
    {
        if (in_array($type, ['integer', 'number', 'percentage'], true) && is_numeric($value)) {
            $numericValue = $type === 'percentage' ? (float) $value / 100 : (float) $value;
            $sheet->setCellValue($cell, $numericValue);
            if ($type === 'percentage') {
                $sheet->getStyle($cell)->getNumberFormat()->setFormatCode('0.00%');
            }
            return;
        }

        $sheet->setCellValueExplicit($cell, $this->safeText($value), DataType::TYPE_STRING);
    }

    private function safeSheetTitle(string $title, Spreadsheet $spreadsheet): string
    {
        $title = str_replace(['\\', '/', '*', '?', ':', '[', ']'], '', $title) ?: 'Report section';
        $title = mb_substr($title, 0, 31);
        $candidate = $title;
        $counter = 2;
        while ($spreadsheet->sheetNameExists($candidate)) {
            $suffix = ' '.$counter++;
            $candidate = mb_substr($title, 0, 31 - mb_strlen($suffix)).$suffix;
        }

        return $candidate;
    }

    private function columnName(int $number): string
    {
        $name = '';
        while ($number > 0) {
            $remainder = ($number - 1) % 26;
            $name = chr(65 + $remainder).$name;
            $number = (int) floor(($number - 1) / 26);
        }

        return $name;
    }

    private function safeText(mixed $value): string
    {
        $value = (string) ($value ?? '');

        return preg_match('/^[\s\x{FEFF}]*[=+@-]|^[\t\r\n]/u', $value) ? "'".$value : $value;
    }
}
