<?php

namespace App\Services\Reports\Exports;

use App\Services\Reports\OfficialReportBranding;
use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\PhpWord;
use PhpOffice\PhpWord\SimpleType\Jc;
use PhpOffice\PhpWord\SimpleType\JcTable;
use PhpOffice\PhpWord\Style\Section;

final class ReportWordExporter
{
    public function __construct(private readonly OfficialReportBranding $branding)
    {
    }

    public function download(array $report, string $filename)
    {
        $phpWord = new PhpWord;
        $phpWord->setDefaultFontName('Arial');
        $phpWord->setDefaultFontSize(9);
        $branding = $this->branding->data();
        $columnCounts = [count($report['columns'])];
        foreach ($report['sections'] ?? [] as $reportSection) {
            if (($reportSection['kind'] ?? null) === 'table') {
                $columnCounts[] = count($reportSection['columns'] ?? []);
            }
        }

        $section = $phpWord->addSection([
            'orientation' => max($columnCounts) > 7 ? Section::ORIENTATION_LANDSCAPE : Section::ORIENTATION_PORTRAIT,
            'marginTop' => 720,
            'marginRight' => 720,
            'marginBottom' => 720,
            'marginLeft' => 720,
        ]);

        if ($branding['logo_path'] !== null) {
            $section->addImage($branding['logo_path'], [
                'width' => 76,
                'height' => 45,
                'alignment' => Jc::CENTER,
            ]);
        }

        $section->addText($branding['government'], [
            'bold' => true,
            'size' => 12,
            'color' => '1E3A8A',
        ], ['alignment' => Jc::CENTER, 'spaceAfter' => 0]);
        $section->addText($branding['ministry'], [
            'bold' => true,
            'size' => 11,
            'color' => '0F766E',
        ], ['alignment' => Jc::CENTER, 'spaceAfter' => 120]);
        $section->addText($report['title'], ['bold' => true, 'size' => 14], ['alignment' => Jc::CENTER, 'spaceAfter' => 60]);
        $section->addText('Reporting period: '.$report['period'], ['size' => 9], ['alignment' => Jc::CENTER]);
        $section->addText('Generated on: '.($report['generated_at_label'] ?? $report['generated_at']).' | Generated by: '.$report['generated_by'], ['size' => 8, 'color' => '64748B'], ['alignment' => Jc::CENTER, 'spaceAfter' => 180]);

        $section->addText('Applied filters', ['bold' => true, 'color' => '1E3A8A'], ['spaceAfter' => 40]);
        foreach ($report['filters'] as $label => $value) {
            $section->addText($label.': '.$value, ['size' => 8], ['spaceAfter' => 0]);
        }

        if (! empty($report['summary'])) {
            $section->addTextBreak(1);
            $section->addText('Summary', ['bold' => true, 'color' => '1E3A8A'], ['spaceAfter' => 40]);
            foreach ($report['summary'] as $label => $value) {
                $section->addText(str_replace('_', ' ', $label).': '.(string) $value, ['size' => 8], ['spaceAfter' => 0]);
            }
        }

        if (! empty($report['sections'])) {
            foreach ($report['sections'] as $reportSection) {
                $section->addTextBreak(1);
                $section->addText($reportSection['title'], ['bold' => true, 'color' => '1E3A8A', 'size' => 10], ['spaceAfter' => 50]);

                if (($reportSection['kind'] ?? '') === 'text') {
                    $section->addText((string) ($reportSection['text'] ?? ''), ['size' => 9], ['spaceAfter' => 60]);
                } elseif (($reportSection['kind'] ?? '') === 'list') {
                    foreach ($reportSection['items'] ?? [] as $item) {
                        $section->addText('• '.(string) $item, ['size' => 8], ['spaceAfter' => 20]);
                    }
                } elseif (($reportSection['kind'] ?? '') === 'metrics') {
                    foreach ($reportSection['metrics'] ?? [] as $metric) {
                        $section->addText((string) $metric['label'].': '.(string) ($metric['value'] ?? '—'), ['size' => 8], ['spaceAfter' => 0]);
                    }
                } elseif (($reportSection['kind'] ?? '') === 'table') {
                    $this->addTable($section, $reportSection['columns'] ?? [], $reportSection['rows'] ?? []);
                }
            }
        } else {
            $section->addTextBreak(1);
            $this->addTable($section, $report['columns'], $report['rows'], ($report['pagination']['total'] ?? 0) === 0);
        }

        $footer = $section->addFooter();
        $footer->addText('Ministry of Health Zanzibar | '.$report['title'].' | Page ', ['size' => 8, 'color' => '64748B'], ['alignment' => Jc::CENTER]);
        $footer->addField('PAGE');
        $footer->addText(' of ', ['size' => 8, 'color' => '64748B']);
        $footer->addField('NUMPAGES');

        $path = tempnam(sys_get_temp_dir(), 'report-docx-');
        $writer = IOFactory::createWriter($phpWord, 'Word2007');
        $previousEscaping = \PhpOffice\PhpWord\Settings::isOutputEscapingEnabled();
        try {
            // Clinical notes and hospital names are plain text, not raw XML.
            \PhpOffice\PhpWord\Settings::setOutputEscapingEnabled(true);
            $writer->save($path);
        } finally {
            \PhpOffice\PhpWord\Settings::setOutputEscapingEnabled($previousEscaping);
        }

        return response()->download(
            $path,
            $filename,
            ['Content-Type' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
        )->deleteFileAfterSend(true);
    }

    private function cellValue(mixed $value, string $type): string
    {
        if ($value === null || $value === '') {
            return '';
        }

        if ($type === 'percentage' && is_numeric($value)) {
            return number_format((float) $value, 2).'%';
        }

        if (in_array($type, ['integer', 'number'], true) && is_numeric($value)) {
            return number_format((float) $value);
        }

        return (string) $value;
    }

    private function addTable($section, array $columns, array $rows, bool $empty = false): void
    {
        $table = $section->addTable([
            'borderSize' => 6,
            'borderColor' => 'CBD5E1',
            'cellMargin' => 70,
            'alignment' => JcTable::CENTER,
        ]);
        $headerStyle = ['bold' => true, 'color' => 'FFFFFF', 'size' => 8];
        $headerCellStyle = ['bgColor' => '1D4ED8', 'valign' => 'center'];
        $cellStyle = ['size' => 8];

        $headerRow = $table->addRow();
        $headerRow->getStyle()->setTblHeader(true);
        foreach ($columns as $column) {
            $table->addCell(null, $headerCellStyle)->addText($column['label'], $headerStyle);
        }

        foreach ($rows as $row) {
            $table->addRow();
            foreach ($columns as $column) {
                $table->addCell(null, ['valign' => 'top'])->addText($this->cellValue($row[$column['key']] ?? null, $column['type'] ?? 'text'), $cellStyle);
            }
        }

        if ($empty || $rows === []) {
            $table->addRow();
            $table->addCell(null, ['gridSpan' => max(count($columns), 1)])->addText('No records were found for the selected criteria.', $cellStyle);
        }
    }
}
